name: CI fichier appel reusable-file
on:
  pull_request:
    branches:
      - main
jobs:
  call-workflow:
    uses: Brice-Lethimonnier/SESSION-6/.github/workflows/semgrep.yml@main
    with:
      repertoire : '.'
      vuln_bloque : false
      semgrep : true
      codeql : true
      
