name: CI fichier appel reusable-file
on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read
  actions: read
  id-token: write
  security-events: write
  
jobs:
  call-workflow:
    uses: ./.github/workflows/semgrep.yml
    with:
      repertoire: '.'
      vuln_bloque: false
      semgrep: true
      codeql: true
      _contents: 'read'
      _actions: 'read'
      _id-token: 'write'
      _sec-events: 'write'
      
        
        
      
      
