name: CI fichier appel reusable-file
on:
  pull_request:
    branches:
      - main
jobs:
  call-workflow:
    uses: Brice-Lethimonnier/SESSION_6/.github/workflows/semgrep.yml
    with:
      config-path: .github/labeler.yml
