name: Call a reusable workflow
on:
  pull_request:
    branches:
      - main
jobs:
  call-workflow:
    uses: Brice-Lethimonnier/SESSION_6/.github/workflows/semgrep.yml
    with:
      config-path: .github/labeler.yml
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
