name: CI fichier appel reusable-file
on:
  pull_request:
    branches:
      - main
jobs:
  call-workflow:
    uses: ./.github/workflows/semgrep.yml
    with:
      repertoire: '.'
      vuln_bloque: false
      semgrep: true
      codeql: true
      _contents: 'read'
      _actions: 'read'
      _id-token: 'write'
      _sec-events: 'write'
      
        
        
      
      
