name: CI fichier appel reusable-file
on:
  pull_request:
    branches:
      - main
jobs:
  call-workflow:
    uses: Brice-Lethimonnier/SESSION-6/.github/workflows/semgrep.yml@main
    with:
      config-path: .github/config.yml
