name: Semgrep Analysis

on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string
      commit:
        required: true
        type: string
      is-bloking:
        required: true
        type: boolean
        default: false

jobs:
  semgrep:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Semgrep
        run: |
          semgrep --config <your-config> --sarif --output semgrep-results.sarif

      - name: Upload SARIF results
        run: |
          codeql github upload-results \
            --repository=${{ github.repository }} \
            --ref=${{ inputs.ref }} \
            --commit=${{ inputs.commit }} \
            --sarif=semgrep-results.sarif
