# Nom Action Github
name: Semgrep.yml
on:
  workflow_call:
    inputs:
      repertoire:
        default: '.'
        required : false
        type: string
      vuln_bloque:
        default: false
        required: false
        type: boolean
      _semgrep:
        default: true
        required: false
        type: boolean
      _contents:
        default: 'read'
        required: false
        type: string
      _actions:
        default: 'read'
        required: false
        type: string
      _id-token:
        default: 'read'
        required: false
        type: string
      _sec-events:
        default: 'write'
        required: false
        type: string
      -codeql:
        default: true
        required: false
        type: boolean
        



  # Scan mainline branches and report all findings:
push:
  branches: ["main"]

      
permissions:
    contents : ${{inputs._contents}}
    actions: ${{inputs._actions}}
    id-token: ${{inputs._id-token}}
    security-events: ${{inputs._sec-events}}


jobs:
  semgrep:
    # User definable name of this GitHub Actions job.
    name: semgrep/ci
    # If you are self-hosting, change the following `runs-on` value:
    runs-on: [self-hosted]
    permissions:
      # required for all workflows
      security-events: ${{inputs._sec-events}}
      # only required for workflows in private repositories
      actions: ${{inputs._actions}}
      contents: ${{inputs._contents}}

    steps:
      # Fetch project source with GitHub Actions Checkout.
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: setup python3
        uses: actions/setup-python@5
        with:
          python-version: '3.12'

      - name: Installation Semgrep
        run: |
          python -m pip install --upgrade pip
          pip intall semgrep
          semgrep --version

      - name: run Semgrep 
        run : semgrep scan -q --sarif --config auto ${{inputs.repertoire}}> semgrep-results.sarif

      - name:  mise a jour du fichier semgrep-results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep-results.sarif
          category: semgrep-sast-analysis
          
        
